import type { GameEvent } from './types';

export const COMMUNITY_NAMES = [
  'The Patch Notes Club',
  'Tiny Volcano Forum',
  'The Very Normal Group',
  'Comment Goblin Union',
  'The Button Pressers',
  'Forum of Questionable Wisdom',
  'The Side Quest Society',
  'The Unpaid Internets',
  'The Hot Take Habitat',
  'The Mod Queue Aquarium',
  'The Polite Flame Pit',
  'Definitely Not a Cult Board',
  'The Thread Bakery',
  'The Microdrama Museum',
  'Low Stakes High Council',
  'The Archive Basement',
  'The Widget Complaint Desk',
  'The Infinite Sidebar',
  'The Pinboard Republic',
  'The Vibes Committee',
  'The Broken Poll Society',
  'The Ambient Notification Club',
  'The Rule Napkin Forum',
  'The Half Remembered Wiki',
] satisfies [string, ...string[]];

export const pickCommunityName = (seed: number): string =>
  COMMUNITY_NAMES[Math.abs(seed) % COMMUNITY_NAMES.length] ?? COMMUNITY_NAMES[0];

export const GAME_EVENTS = [
  {
    id: 'power_user_problem',
    arc: 'The Power User arc',
    title: 'The Power User Problem',
    text: 'A beloved regular is insulting new members, but their posts bring half the community activity. The community is split.',
    severity: 4,
    tags: ['power-user', 'new-users', 'discipline'],
    unlockConditions: {},
    choices: [
      {
        id: 'banhammer',
        label: 'Bonk With Banhammer',
        description: 'Remove the legend and survive the fan club.',
        effects: { trust: 10, quality: 8, growth: -6, drama: 12, modStress: 5 },
        consequence:
          'The ban calms new users, but veterans start a protest thread titled "This Place Changed."',
        tags: ['ban', 'restrict', 'power-user'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'private_warning',
        label: 'DM Them Like An Adult',
        description: 'Attempt diplomacy before everyone screenshots it.',
        effects: { trust: 4, quality: 3, drama: 3, modStress: 4 },
        consequence:
          'The situation cools down for now, but everyone screenshots the warning anyway.',
        tags: ['calm', 'power-user'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'content_flow',
        label: 'Numbers Go Brrr',
        description: 'Ignore the mess because traffic is traffic.',
        effects: { growth: 8, trust: -8, quality: -10, drama: 8 },
        consequence: 'Activity spikes, but new users begin quietly leaving.',
        tags: ['growth', 'new-user-exodus'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'make_mod',
        label: 'Promote the Problem',
        description: 'Give the chaos a badge and a clipboard.',
        effects: { growth: 12, drama: 15, trust: -12, modStress: 10 },
        consequence: 'Engagement explodes. So does the mod queue.',
        tags: ['chaos', 'mod-war', 'power-user'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'bot_joke_flood',
    arc: 'The Bot Invasion arc',
    title: 'Suspiciously Similar Jokes',
    text: 'Bot accounts flood the forum with the same joke, each one slightly worse and weirdly confident.',
    severity: 3,
    tags: ['bots', 'spam', 'meme'],
    unlockConditions: {},
    choices: [
      {
        id: 'captcha_wall',
        label: 'Build a CAPTCHA Wall',
        description: 'Make newcomers prove they can identify a chair.',
        effects: { trust: 5, quality: 10, growth: -8, modStress: 7 },
        consequence: 'The bots slow down. So do real people with normal patience.',
        tags: ['restrict', 'bots', 'new-users'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'bot_honeypot',
        label: 'Create a Bot Honeypot',
        description: 'Post bait and quietly tag the repeat offenders.',
        effects: { quality: 6, trust: 4, modStress: 6, drama: 2 },
        consequence: 'The mod team catches a swarm and develops spreadsheet eyes.',
        tags: ['bots', 'investigate'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'embrace_bot_bits',
        label: 'Embrace the Bot Bits',
        description: 'Pretend the repetition is performance art.',
        effects: { growth: 9, drama: 7, quality: -9, reputation: 3 },
        consequence: 'The joke becomes lore and then immediately becomes unbearable.',
        tags: ['meme', 'bots', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
      {
        id: 'ban_repeating_phrases',
        label: 'Ban Repeating Phrases',
        description: 'Filter every copy-paste punchline.',
        effects: { quality: 8, drama: 6, growth: -3, modStress: 5 },
        consequence: 'The phrase vanishes, then users discover fourteen misspellings.',
        tags: ['ban', 'restrict', 'bots'],
        roleAffinity: 'Banhammer Enthusiast',
      },
    ],
  },
  {
    id: 'sponsor_pinned_posts',
    arc: 'The Sponsor Temptation arc',
    title: 'The Sponsored Pin Offer',
    text: 'A sponsor offers money for pinned posts about a productivity drink that appears to contain lightning and regret.',
    severity: 4,
    tags: ['sponsor', 'money', 'reputation'],
    unlockConditions: {},
    choices: [
      {
        id: 'reject_sponsor',
        label: 'Reject the Sponsor',
        description: 'Keep the pinboard clean and smug.',
        effects: { trust: 9, reputation: 6, growth: -2 },
        consequence: 'Users applaud the principle and immediately ask who pays server costs.',
        tags: ['trust', 'sponsor'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'clearly_label_ad',
        label: 'Label It Loudly',
        description: 'Take the deal with giant disclosure text.',
        effects: { growth: 7, reputation: 4, trust: -2, quality: -3, modStress: 3 },
        consequence: 'The community accepts the money but debates font size for six hours.',
        tags: ['sponsor', 'growth'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'quiet_ad_pin',
        label: 'Quietly Pin It',
        description: 'Act casual and hope nobody reads the label.',
        effects: { growth: 12, quality: -10, trust: -14, reputation: -8, drama: 12 },
        consequence: 'Everyone reads the label. The label becomes evidence.',
        tags: ['sponsor', 'drama', 'quality-drop'],
        roleAffinity: 'Sponsor Gremlin',
      },
      {
        id: 'community_vote_ad',
        label: 'Make It a Vote',
        description: 'Let the community decide whether money is cursed.',
        effects: { trust: 5, drama: 9, modStress: 5, reputation: 2 },
        consequence: 'The vote is transparent, passionate, and somehow tied.',
        tags: ['vote', 'sponsor'],
        roleAffinity: 'Community Therapist',
      },
    ],
  },
  {
    id: 'journalist_questions',
    arc: 'The Journalist Watching arc',
    title: 'A Journalist Is Watching',
    text: 'A reporter asks polite questions about why the community has a 47-page argument about soup etiquette.',
    severity: 3,
    tags: ['journalist', 'reputation', 'public'],
    unlockConditions: {},
    choices: [
      {
        id: 'give_tour',
        label: 'Give a Guided Tour',
        description: 'Explain the lore before the lore explains itself.',
        effects: { reputation: 10, trust: 3, modStress: 4 },
        consequence: 'The article is fair, but users now perform normality too loudly.',
        tags: ['journalist', 'reputation'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'no_comment',
        label: 'Say No Comment',
        description: 'Close ranks and hope mystery reads as dignity.',
        effects: { trust: 4, reputation: -5, drama: 5 },
        consequence: 'The silence becomes its own paragraph.',
        tags: ['journalist', 'drama'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'stage_showcase',
        label: 'Stage a Showcase Thread',
        description: 'Ask everyone to be impressive for one day.',
        effects: { reputation: 12, quality: 5, trust: -4, modStress: 8 },
        consequence: 'The showcase works until someone links the soup archive.',
        tags: ['journalist', 'quality'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'feed_the_story',
        label: 'Feed the Story',
        description: 'Lean into the spectacle for traffic.',
        effects: { growth: 14, reputation: 6, drama: 14, quality: -8 },
        consequence: 'The community trends, mostly as a warning.',
        tags: ['journalist', 'growth', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'rules_too_confusing',
    arc: 'The New User Exodus arc',
    title: 'The Rules Are Impossible',
    text: 'New users complain the rules read like a tax form written during a thunderstorm.',
    severity: 3,
    tags: ['new-users', 'rules', 'quality'],
    unlockConditions: {},
    choices: [
      {
        id: 'rewrite_rules',
        label: 'Rewrite the Rules',
        description: 'Make the whole thing human-readable.',
        effects: { trust: 8, growth: 5, quality: 4, modStress: 8 },
        consequence: 'Everyone likes the new rules except people whose hobby was parsing the old ones.',
        tags: ['rules', 'new-users'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'rules_flowchart',
        label: 'Publish a Flowchart',
        description: 'Turn policy into a slightly alarming diagram.',
        effects: { quality: 8, trust: 3, modStress: 4, drama: 3 },
        consequence: 'The flowchart helps, then becomes a meme template.',
        tags: ['rules', 'meme'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'pin_ask_anything',
        label: 'Pin Ask Anything',
        description: 'Invite confused newcomers into one safe thread.',
        effects: { trust: 6, growth: 7, quality: -2, modStress: 6 },
        consequence: 'New users arrive. So do veterans answering like tired riddles.',
        tags: ['new-users', 'growth'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'keep_gatekeeping',
        label: 'Keep the Maze',
        description: 'Argue that confusion protects the culture.',
        effects: { quality: 4, growth: -10, trust: -8, drama: 6, modStress: -2 },
        consequence: 'The old guard nods. The signup graph winces.',
        tags: ['new-user-exodus', 'rules'],
        roleAffinity: 'Quality Purist',
      },
    ],
  },
  {
    id: 'ancient_rule_return',
    arc: 'The Ancient Forum Lore arc',
    title: 'Bring Back Rule Zero',
    text: 'Old users demand the return of an ancient rule banning posts that "feel sideways".',
    severity: 2,
    tags: ['lore', 'rules', 'veterans'],
    unlockConditions: {},
    choices: [
      {
        id: 'restore_rule_zero',
        label: 'Restore Rule Zero',
        description: 'Honour the archives and fear the sideways.',
        effects: { quality: 7, trust: -3, growth: -4, drama: 7 },
        consequence: 'Veterans cheer while new users ask what direction posts should face.',
        tags: ['lore', 'restrict', 'rules'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'museum_rule',
        label: 'Put It in the Museum',
        description: 'Celebrate the rule without enforcing it.',
        effects: { trust: 5, reputation: 4, drama: -2 },
        consequence: 'The wiki gains a dusty exhibit and the argument loses oxygen.',
        tags: ['lore', 'calm'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'modernise_rule',
        label: 'Modernise the Rule',
        description: 'Translate folklore into actual moderation language.',
        effects: { quality: 8, trust: 4, modStress: 6 },
        consequence: 'The rule now makes sense, which upsets the mythology department.',
        tags: ['lore', 'rules', 'quality'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'sideways_week',
        label: 'Declare Sideways Week',
        description: 'Turn the old ban into a festival.',
        effects: { growth: 9, drama: 8, quality: -5, reputation: 5 },
        consequence: 'The community celebrates by posting things nobody can categorise.',
        tags: ['lore', 'meme', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'algorithm_blessing',
    arc: 'The Algorithm Blessing arc',
    title: 'The Algorithm Notices You',
    text: 'The feed suddenly boosts the community. Thousands arrive holding questions, opinions, and no context.',
    severity: 4,
    tags: ['algorithm', 'growth', 'new-users'],
    unlockConditions: {},
    choices: [
      {
        id: 'welcome_wave',
        label: 'Welcome the Wave',
        description: 'Open the doors and teach the customs.',
        effects: { growth: 13, trust: 4, modStress: 9, quality: -3 },
        consequence: 'The place grows fast and the regulars start speaking in onboarding copy.',
        tags: ['algorithm', 'growth', 'new-users'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'slow_mode',
        label: 'Enable Slow Mode',
        description: 'Throttle posts until the queue stops smoking.',
        effects: { quality: 9, modStress: -4, growth: -7, drama: 5 },
        consequence: 'The queue stabilises, but visitors complain the forum has loading screen energy.',
        tags: ['restrict', 'algorithm'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'front_page_playbook',
        label: 'Run a Front Page Playbook',
        description: 'Curate high-quality posts for the influx.',
        effects: { reputation: 9, growth: 8, quality: 5, modStress: 7 },
        consequence: 'The community looks sharp, and the mods age in real time.',
        tags: ['algorithm', 'quality', 'reputation'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'milk_the_boost',
        label: 'Milk the Boost',
        description: 'Post relentlessly while the feed is warm.',
        effects: { growth: 18, reputation: 4, quality: -12, drama: 9 },
        consequence: 'Numbers soar. Coherence packs a bag.',
        tags: ['algorithm', 'growth', 'quality-drop'],
        roleAffinity: 'Sponsor Gremlin',
      },
    ],
  },
  {
    id: 'meme_too_powerful',
    arc: 'The Meme Economy arc',
    title: 'The Meme Becomes Too Powerful',
    text: 'A meme format takes over every thread. It is funny, then everywhere, then a municipal hazard.',
    severity: 3,
    tags: ['meme', 'quality', 'growth'],
    unlockConditions: {},
    choices: [
      {
        id: 'contain_meme_day',
        label: 'Contain It to Meme Day',
        description: 'Give the joke a weekly paddock.',
        effects: { quality: 7, trust: 4, drama: 4, modStress: 3 },
        consequence: 'The meme survives in captivity and occasionally rattles the fence.',
        tags: ['meme', 'rules'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'ban_format',
        label: 'Ban the Format',
        description: 'End the bit before the bit ends you.',
        effects: { quality: 10, growth: -5, drama: 13, modStress: 4 },
        consequence: 'The format dies loudly and returns as a protest format.',
        tags: ['ban', 'meme', 'restrict'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'meme_competition',
        label: 'Host a Meme Contest',
        description: 'Concentrate the energy into one glorious bracket.',
        effects: { growth: 10, reputation: 5, drama: 6, quality: -3, modStress: 5 },
        consequence: 'The bracket is popular until accusations of format fraud emerge.',
        tags: ['meme', 'growth'],
        roleAffinity: 'Drama Farmer',
      },
      {
        id: 'let_it_evolve',
        label: 'Let It Evolve',
        description: 'Trust the culture to metabolise itself.',
        effects: { growth: 8, drama: 5, quality: -7, trust: 2 },
        consequence: 'The meme mutates into something shorter, louder, and harder to explain.',
        tags: ['meme', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'mod_leak',
    arc: 'The Mod Team Civil War arc',
    title: 'The Mod Chat Leaks',
    text: 'Private mod arguments leak, revealing a bitter dispute over flair colours and one ominous spreadsheet.',
    severity: 5,
    tags: ['mod-war', 'leak', 'trust'],
    unlockConditions: {},
    choices: [
      {
        id: 'publish_statement',
        label: 'Publish a Statement',
        description: 'Own the mess with adult sentences.',
        effects: { trust: 7, reputation: 4, drama: 8, modStress: 6 },
        consequence: 'The statement helps, though everyone reads it like a court document.',
        tags: ['mod-war', 'reputation'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'remove_leaker',
        label: 'Remove the Leaker',
        description: 'Defend the sanctity of the spreadsheet.',
        effects: { modStress: -3, drama: 14, trust: -7, quality: 3 },
        consequence: 'The leak stops. The speculation receives a season two.',
        tags: ['remove', 'mod-war', 'restrict'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'open_mod_minutes',
        label: 'Open Mod Minutes',
        description: 'Make future decisions visible.',
        effects: { trust: 11, modStress: 10, drama: 3, reputation: 5 },
        consequence: 'Transparency rises, along with comments about punctuation in the minutes.',
        tags: ['mod-war', 'trust'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'let_mods_duel',
        label: 'Let Mods Duel Publicly',
        description: 'Turn the dispute into a structured debate.',
        effects: { growth: 13, drama: 17, trust: -10, modStress: 12 },
        consequence: 'The debate draws a crowd and convinces nobody of anything healthy.',
        tags: ['mod-war', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'fake_expert',
    arc: 'The Journalist Watching arc',
    title: 'The Fake Expert Ascends',
    text: 'A user with impressive formatting becomes the trusted expert, despite being wrong in unusually confident paragraphs.',
    severity: 4,
    tags: ['expert', 'quality', 'reputation'],
    unlockConditions: {},
    choices: [
      {
        id: 'ask_sources',
        label: 'Require Sources',
        description: 'Make claims carry receipts.',
        effects: { quality: 12, trust: 5, growth: -4, modStress: 6 },
        consequence: 'The expert posts fewer claims and more dramatic ellipses.',
        tags: ['quality', 'rules'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'expert_flair_review',
        label: 'Review Expert Flair',
        description: 'Audit credentials without starting a credential war.',
        effects: { quality: 8, reputation: 6, drama: 7, modStress: 7 },
        consequence: 'The review helps and also invents five new arguments about expertise.',
        tags: ['quality', 'reputation'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'let_crowd_correct',
        label: 'Let the Crowd Correct',
        description: 'Trust replies to sort truth from typography.',
        effects: { growth: 5, drama: 8, quality: -6, modStress: -2 },
        consequence: 'Corrections arrive, buried under applause for the formatting.',
        tags: ['drama', 'expert'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'make_expert_ama',
        label: 'Book an AMA',
        description: 'Expose the expert to live questions.',
        effects: { growth: 10, drama: 12, reputation: -5, quality: -4 },
        consequence: 'The AMA is educational in the way a warning sign is educational.',
        tags: ['ama', 'chaos', 'expert'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'wholesome_drama',
    arc: 'The Meme Economy arc',
    title: 'Wholesome Thread, Somehow Drama',
    text: 'A nice appreciation thread turns into a dispute over whether appreciation is becoming mandatory.',
    severity: 2,
    tags: ['wholesome', 'drama', 'culture'],
    unlockConditions: {},
    choices: [
      {
        id: 'thank_everyone',
        label: 'Thank Everyone Anyway',
        description: 'Model the kindness without forcing it.',
        effects: { trust: 8, drama: -4, quality: 2 },
        consequence: 'The thread softens, although three users complain about sincerity tone.',
        tags: ['calm', 'trust'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'ban_meta_kindness',
        label: 'Ban Meta-Kindness',
        description: 'No arguments about appreciation inside appreciation.',
        effects: { quality: 5, drama: 6, modStress: 4, trust: -3 },
        consequence: 'The thread becomes orderly and weirdly tense.',
        tags: ['ban', 'restrict', 'quality'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'weekly_gratitude',
        label: 'Create Gratitude Friday',
        description: 'Give wholesome energy a scheduled outlet.',
        effects: { trust: 6, growth: 4, quality: 3, modStress: 3 },
        consequence: 'Gratitude becomes recurring content, which is lovely and lightly bureaucratic.',
        tags: ['culture', 'growth'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'rank_kindness',
        label: 'Rank the Kindness',
        description: 'Turn appreciation into a leaderboard.',
        effects: { growth: 8, drama: 10, trust: -6, quality: -3 },
        consequence: 'The leaderboard proves that nothing ruins warmth like points.',
        tags: ['chaos', 'growth'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'manifesto_9000',
    arc: 'The Ancient Forum Lore arc',
    title: 'The 9000 Word Manifesto',
    text: 'A user posts a manifesto explaining exactly how the community lost its way, with chapter headings.',
    severity: 3,
    tags: ['manifesto', 'lore', 'drama'],
    unlockConditions: {},
    choices: [
      {
        id: 'pin_manifesto_debate',
        label: 'Pin a Debate Thread',
        description: 'Contain the thesis defence in one place.',
        effects: { trust: 4, drama: 8, modStress: 5, quality: 2 },
        consequence: 'The debate is productive for twelve minutes, then develops footnotes.',
        tags: ['lore', 'drama'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'remove_manifesto',
        label: 'Remove for Length Crimes',
        description: 'Declare the wall of text load-bearing no longer.',
        effects: { quality: 5, drama: 12, trust: -5, modStress: 2 },
        consequence: 'The author posts a shorter manifesto about censorship.',
        tags: ['remove', 'restrict', 'lore'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'summarise_manifesto',
        label: 'Make a Mod Summary',
        description: 'Translate the essay into digestible bullets.',
        effects: { trust: 7, quality: 6, modStress: 6 },
        consequence: 'The summary helps, and everyone argues about what was omitted.',
        tags: ['quality', 'lore'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'manifesto_book_club',
        label: 'Start a Book Club',
        description: 'Read it weekly until meaning collapses.',
        effects: { growth: 6, drama: 9, reputation: 3, quality: -2 },
        consequence: 'The manifesto becomes canon. Nobody remembers chapter four correctly.',
        tags: ['lore', 'meme', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'rival_raid',
    arc: 'The Mod Team Civil War arc',
    title: 'The Rival Community Raid',
    text: 'A rival forum sends users to flood comments with smug catchphrases and suspicious politeness.',
    severity: 5,
    tags: ['raid', 'mods', 'trust'],
    unlockConditions: {},
    choices: [
      {
        id: 'lock_threads',
        label: 'Lock the Hot Threads',
        description: 'Freeze the targets before the flood spreads.',
        effects: { modStress: -4, drama: 8, quality: 5, trust: -3, growth: -5 },
        consequence: 'The raid loses momentum, and locals complain about frozen conversations.',
        tags: ['lock', 'restrict', 'raid'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'welcome_good_faith',
        label: 'Welcome Good Faith Visitors',
        description: 'Separate curious people from raiders.',
        effects: { trust: 6, growth: 6, modStress: 8, drama: 4 },
        consequence: 'Some visitors stay. Some pretend they were visiting ironically.',
        tags: ['new-users', 'raid'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'counter_meme',
        label: 'Launch a Counter-Meme',
        description: 'Defend the forum with jokes and velocity.',
        effects: { growth: 9, drama: 13, reputation: 4, quality: -4 },
        consequence: 'The counter-meme wins hearts and absolutely worsens the incident report.',
        tags: ['meme', 'raid', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
      {
        id: 'modmail_rival',
        label: 'Message Their Mods',
        description: 'Try diplomacy across the canyon.',
        effects: { trust: 4, reputation: 5, modStress: 5, drama: -3 },
        consequence: 'The rival mods respond with civility and a spreadsheet of denials.',
        tags: ['calm', 'raid'],
        roleAffinity: 'Peacekeeper',
      },
    ],
  },
  {
    id: 'controversial_poll',
    arc: 'The Power User arc',
    title: 'The Poll Splits Everything',
    text: 'A poll about a tiny policy becomes a referendum on the soul of the community.',
    severity: 4,
    tags: ['poll', 'drama', 'rules'],
    unlockConditions: {},
    choices: [
      {
        id: 'honour_poll',
        label: 'Honour the Poll',
        description: 'Accept the result, even if it looks cursed.',
        effects: { trust: 6, drama: 7, quality: -3, modStress: 2 },
        consequence: 'Democracy happens and immediately asks for a recount.',
        tags: ['vote', 'poll'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'rerun_better_poll',
        label: 'Rerun It Better',
        description: 'Fix the wording and invite fresh outrage.',
        effects: { trust: 3, quality: 4, drama: 9, modStress: 5 },
        consequence: 'The second poll is clearer and somehow more controversial.',
        tags: ['poll', 'rules'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'ignore_poll',
        label: 'Ignore the Poll',
        description: 'Call it advisory and duck under the table.',
        effects: { trust: -12, drama: 11, modStress: -2, quality: 2 },
        consequence: 'The word advisory becomes a curse.',
        tags: ['drama', 'poll'],
        roleAffinity: 'Drama Farmer',
      },
      {
        id: 'poll_playoffs',
        label: 'Create Poll Playoffs',
        description: 'Turn policy into an elimination bracket.',
        effects: { growth: 10, drama: 12, quality: -5, reputation: 3 },
        consequence: 'The bracket is thrilling until policy has a quarter-final upset.',
        tags: ['poll', 'growth', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'celebrity_joins',
    arc: 'The Algorithm Blessing arc',
    title: 'A Celebrity Joins',
    text: 'A minor celebrity posts casually and the community forgets how chairs work.',
    severity: 4,
    tags: ['celebrity', 'growth', 'reputation'],
    unlockConditions: {},
    choices: [
      {
        id: 'normal_rules_apply',
        label: 'Apply Normal Rules',
        description: 'Treat fame like any other flairless account.',
        effects: { trust: 7, quality: 5, reputation: 3, drama: 5 },
        consequence: 'The celebrity stays, impressed by the community being weirdly fair.',
        tags: ['quality', 'celebrity'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'celebrity_ama',
        label: 'Ask for an AMA',
        description: 'Channel the attention into a scheduled event.',
        effects: { growth: 14, reputation: 10, modStress: 9, quality: -2 },
        consequence: 'The AMA draws a crowd and one question about soup etiquette.',
        tags: ['ama', 'celebrity', 'growth'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'protect_celebrity',
        label: 'Protect Them Aggressively',
        description: 'Remove anything that could scare the guest.',
        effects: { reputation: 5, trust: -7, drama: 10, modStress: 6, quality: 3 },
        consequence: 'The celebrity is safe, and users accuse the mods of velvet ropes.',
        tags: ['remove', 'restrict', 'celebrity'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'turn_into_bit',
        label: 'Turn It Into a Bit',
        description: 'Make the visit part of the culture instantly.',
        effects: { growth: 12, drama: 8, quality: -6, reputation: 4 },
        consequence: 'The celebrity laughs once, then the joke becomes everyone else’s job.',
        tags: ['meme', 'celebrity', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'community_conspiracy',
    arc: 'The Ancient Forum Lore arc',
    title: 'The Community Invents a Conspiracy',
    text: 'Users decide the sidebar wording proves a secret council controls which posts get vibes.',
    severity: 3,
    tags: ['conspiracy', 'lore', 'drama'],
    unlockConditions: {},
    choices: [
      {
        id: 'explain_sidebar',
        label: 'Explain the Sidebar',
        description: 'Show the boring truth with receipts.',
        effects: { trust: 7, drama: -3, quality: 4, modStress: 3 },
        consequence: 'The truth is accepted by everyone except the receipt auditors.',
        tags: ['calm', 'lore'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'rename_secret_council',
        label: 'Rename the Council',
        description: 'Make the joke official enough to deflate it.',
        effects: { trust: 3, growth: 5, drama: 4, reputation: 3 },
        consequence: 'The Secret Council becomes a harmless flair and a deeply annoying catchphrase.',
        tags: ['meme', 'lore'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'ban_conspiracy_threads',
        label: 'Ban Conspiracy Threads',
        description: 'Stop the corkboard from growing legs.',
        effects: { quality: 8, drama: 10, trust: -6, modStress: 4 },
        consequence: 'The ban convinces conspiracy fans they were close.',
        tags: ['ban', 'restrict', 'conspiracy'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'host_lore_trial',
        label: 'Host a Lore Trial',
        description: 'Let users prosecute the sidebar in public.',
        effects: { growth: 9, drama: 13, reputation: 5, quality: -4 },
        consequence: 'The trial trends, and the sidebar pleads no contest.',
        tags: ['lore', 'chaos', 'growth'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'rule_about_rules',
    arc: 'The New User Exodus arc',
    title: 'A Rule About Asking for Rules',
    text: 'Someone asks for a rule about asking whether new rules should be proposed in rule threads.',
    severity: 2,
    tags: ['rules', 'meta', 'new-users'],
    unlockConditions: {},
    choices: [
      {
        id: 'meta_rule_megathread',
        label: 'Create a Meta Megathread',
        description: 'Put rule questions in one labelled cupboard.',
        effects: { quality: 6, trust: 4, modStress: 4, drama: 2 },
        consequence: 'The cupboard works until someone asks for shelves.',
        tags: ['rules', 'meta'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'plain_language_policy',
        label: 'Plain Language Policy',
        description: 'Make rule proposals understandable first.',
        effects: { trust: 7, growth: 3, quality: 5, modStress: 3 },
        consequence: 'The proposals improve and the pedants learn new hobbies.',
        tags: ['rules', 'new-users'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'no_rule_rules',
        label: 'No More Rule Rules',
        description: 'Ban recursive policy spirals.',
        effects: { modStress: -4, quality: 4, drama: 7, trust: -2 },
        consequence: 'The spiral stops, then reappears disguised as process feedback.',
        tags: ['ban', 'restrict', 'rules'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'rule_rules_poll',
        label: 'Poll Every Rule Rule',
        description: 'Let process become content.',
        effects: { growth: 6, drama: 9, quality: -3, modStress: 6 },
        consequence: 'The poll is popular, inconclusive, and technically a rule event.',
        tags: ['poll', 'rules', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'comment_roleplay',
    arc: 'The Unhinged AMA arc',
    title: 'The Comment Section Starts Roleplaying',
    text: 'A normal thread becomes a tavern, then a courtroom, then a weather system with opinions.',
    severity: 3,
    tags: ['roleplay', 'comments', 'meme'],
    unlockConditions: {},
    choices: [
      {
        id: 'roleplay_thread_only',
        label: 'One Roleplay Thread',
        description: 'Give the theatre a stage.',
        effects: { trust: 4, quality: 5, drama: 3, modStress: 3 },
        consequence: 'The actors move to the stage, except one fog machine in general chat.',
        tags: ['meme', 'rules'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'improv_week',
        label: 'Declare Improv Week',
        description: 'Let the bit breathe for a limited time.',
        effects: { growth: 9, reputation: 4, quality: -4, drama: 5 },
        consequence: 'The week is funny, then legally becomes a month in spirit.',
        tags: ['meme', 'growth'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'ban_roleplay',
        label: 'Ban Roleplay',
        description: 'Restore normal comments with suspicious speed.',
        effects: { quality: 8, drama: 9, trust: -4, modStress: 2 },
        consequence: 'The tavern closes. Users whisper in medieval metaphors anyway.',
        tags: ['ban', 'restrict'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'mod_in_character',
        label: 'Moderate In Character',
        description: 'Answer reports as the tavern bailiff.',
        effects: { growth: 8, drama: 11, reputation: 6, modStress: 8, trust: -5 },
        consequence: 'The community loves it until a ban appeal arrives written as a sea shanty.',
        tags: ['chaos', 'roleplay'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'typo_lore',
    arc: 'The Ancient Forum Lore arc',
    title: 'The Typo Becomes Lore',
    text: 'A harmless typo in a mod post becomes a slogan, a flair, and possibly a worldview.',
    severity: 1,
    tags: ['lore', 'typo', 'meme'],
    unlockConditions: {},
    choices: [
      {
        id: 'embrace_typo',
        label: 'Embrace the Typo',
        description: 'Make the mistake a mascot-shaped concept.',
        effects: { trust: 5, growth: 5, reputation: 3, quality: -2 },
        consequence: 'The typo becomes beloved and impossible to explain to outsiders.',
        tags: ['lore', 'meme'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'correct_typo',
        label: 'Correct It Quietly',
        description: 'Fix the post and deny the culture oxygen.',
        effects: { quality: 4, drama: 5, growth: -2 },
        consequence: 'The correction is screenshotted as an attack on heritage.',
        tags: ['quality', 'lore'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'typo_flair',
        label: 'Add Typo Flair',
        description: 'Let users wear the error proudly.',
        effects: { growth: 6, trust: 3, drama: 2, reputation: 3 },
        consequence: 'The flair spreads, then becomes a class identity.',
        tags: ['lore', 'growth'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'ban_typo_jokes',
        label: 'Ban Typo Jokes',
        description: 'Protect everyone from the bit before it colonises language.',
        effects: { quality: 5, drama: 10, trust: -4, modStress: 2 },
        consequence: 'The joke becomes funnier because it is forbidden.',
        tags: ['ban', 'restrict', 'lore'],
        roleAffinity: 'Banhammer Enthusiast',
      },
    ],
  },
  {
    id: 'absurd_mod_queue',
    arc: 'The Mod Team Civil War arc',
    title: 'The Mod Queue Hits Four Digits',
    text: 'The queue reaches an absurd size and begins to feel less like a list and more like weather.',
    severity: 5,
    tags: ['mod-war', 'queue', 'stress'],
    unlockConditions: {},
    choices: [
      {
        id: 'recruit_temp_mods',
        label: 'Recruit Temp Mods',
        description: 'Draft trusted users for emergency triage.',
        effects: { modStress: -10, trust: 3, quality: 4, drama: 6 },
        consequence: 'The queue shrinks, and the temp mods discover power has keyboard shortcuts.',
        tags: ['mods', 'queue'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'auto_close_old_reports',
        label: 'Auto-Close Old Reports',
        description: 'Sweep stale reports into the history bin.',
        effects: { modStress: -13, quality: -7, trust: -5, drama: 5 },
        consequence: 'The number drops fast. So does confidence in the broom.',
        tags: ['queue', 'quality-drop'],
        roleAffinity: 'Sponsor Gremlin',
      },
      {
        id: 'strict_filters',
        label: 'Tighten Filters',
        description: 'Stop more mess from entering.',
        effects: { quality: 9, modStress: -4, growth: -6, drama: 7 },
        consequence: 'The queue breathes while innocent posts wait outside holding paperwork.',
        tags: ['restrict', 'queue'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'queue_livestream',
        label: 'Livestream the Queue',
        description: 'Make moderation visible entertainment.',
        effects: { growth: 10, drama: 14, reputation: 3, trust: -8, modStress: 4 },
        consequence: 'People watch the queue like sports and start fantasy leagues.',
        tags: ['chaos', 'queue', 'growth'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'power_user_fan_club',
    arc: 'The Power User arc',
    title: 'The Power User Fan Club',
    text: 'A regular gains followers who defend every post like it is a fragile national monument.',
    severity: 3,
    tags: ['power-user', 'drama', 'culture'],
    unlockConditions: { minDay: 3, requiredTags: ['power-user'] },
    choices: [
      {
        id: 'no_personality_cults',
        label: 'Ban Personality Cults',
        description: 'Make the culture about posts, not posters.',
        effects: { quality: 8, trust: 4, drama: 9, growth: -3 },
        consequence: 'The rule helps, and fans start calling themselves a discussion group.',
        tags: ['ban', 'restrict', 'power-user'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'spotlight_many_users',
        label: 'Spotlight More Users',
        description: 'Dilute celebrity with a wider stage.',
        effects: { trust: 7, growth: 5, quality: 3, modStress: 4 },
        consequence: 'The spotlight spreads and the fan club loses monopoly power.',
        tags: ['growth', 'power-user'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'let_fandom_run',
        label: 'Let Fandom Run',
        description: 'Accept that parasocial weather drives traffic.',
        effects: { growth: 10, drama: 8, quality: -8, trust: -5 },
        consequence: 'The fan club recruits faster than the rules can blink.',
        tags: ['growth', 'power-user'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'fan_club_flair',
        label: 'Give Them Flair',
        description: 'Make the faction visible and therefore worse.',
        effects: { growth: 8, drama: 13, reputation: 3, trust: -6 },
        consequence: 'The flair turns discourse into team sports.',
        tags: ['chaos', 'power-user'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'bot_apology',
    arc: 'The Bot Invasion arc',
    title: 'The Bot Apologises',
    text: 'A suspected bot posts a heartfelt apology that is either touching or generated by a toaster with ambition.',
    severity: 3,
    tags: ['bots', 'trust', 'weird'],
    unlockConditions: { minDay: 3, requiredTags: ['bots'] },
    choices: [
      {
        id: 'verify_bot',
        label: 'Verify Before Mercy',
        description: 'Ask for proof without creating a circus.',
        effects: { trust: 4, quality: 7, modStress: 5 },
        consequence: 'Verification works, but everyone debates what counts as a soul.',
        tags: ['bots', 'quality'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'forgive_bot',
        label: 'Forgive the Bot',
        description: 'Let redemption have suspicious syntax.',
        effects: { trust: 5, growth: 4, drama: 6, quality: -4 },
        consequence: 'The apology becomes famous and other bots discover feelings.',
        tags: ['bots', 'growth'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'ban_sentimental_bots',
        label: 'Ban Sentimental Bots',
        description: 'No machine tears in the queue.',
        effects: { quality: 8, drama: 8, trust: -2, modStress: 2 },
        consequence: 'The bot is gone. The phrase machine tears remains.',
        tags: ['ban', 'bots', 'restrict'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'bot_poetry_slam',
        label: 'Host Bot Poetry',
        description: 'Turn suspicious language into a contest.',
        effects: { growth: 10, drama: 7, reputation: 5, quality: -6 },
        consequence: 'The slam is weirdly moving until the rhymes start repeating.',
        tags: ['bots', 'meme', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'sponsor_wants_data',
    arc: 'The Sponsor Temptation arc',
    title: 'The Sponsor Wants Insights',
    text: 'A sponsor asks for community trend insights, phrased like they are asking to borrow a ladder.',
    severity: 4,
    tags: ['sponsor', 'trust', 'money'],
    unlockConditions: { minDay: 4, requiredTags: ['sponsor'] },
    choices: [
      {
        id: 'share_aggregate_only',
        label: 'Aggregate Only',
        description: 'Share broad, anonymous trends and nothing personal.',
        effects: { reputation: 6, growth: 5, trust: 2, modStress: 4 },
        consequence: 'The sponsor gets a chart and the users get a very clear boundary.',
        tags: ['sponsor', 'trust'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'reject_data_request',
        label: 'Reject the Request',
        description: 'Keep community behaviour out of the deck.',
        effects: { trust: 9, reputation: 2, growth: -4 },
        consequence: 'Users approve, and the sponsor discovers the word alignment.',
        tags: ['sponsor', 'trust'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'sell_vibes_report',
        label: 'Sell a Vibes Report',
        description: 'Package the culture as premium insight.',
        effects: { growth: 10, reputation: 8, trust: -8, quality: -5, drama: 7 },
        consequence: 'The report earns money and gives users a new thing to distrust.',
        tags: ['sponsor', 'quality-drop'],
        roleAffinity: 'Sponsor Gremlin',
      },
      {
        id: 'ask_users_data_poll',
        label: 'Poll the Community',
        description: 'Let everyone argue about invisible lines.',
        effects: { trust: 4, drama: 10, modStress: 5 },
        consequence: 'The poll is spirited, educational, and six subthreads deep.',
        tags: ['sponsor', 'poll'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'journalist_quote_mining',
    arc: 'The Journalist Watching arc',
    title: 'The Quote Mining Panic',
    text: 'Users fear every comment will be quoted out of context in a story about Extremely Online Behaviour.',
    severity: 3,
    tags: ['journalist', 'trust', 'comments'],
    unlockConditions: { minDay: 4, requiredTags: ['journalist'] },
    choices: [
      {
        id: 'quote_context_thread',
        label: 'Create Context Thread',
        description: 'Give outsiders one place to understand the joke.',
        effects: { reputation: 8, trust: 4, quality: 3, modStress: 4 },
        consequence: 'The context thread helps and becomes longer than the article.',
        tags: ['journalist', 'quality'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'temporary_privacy_rules',
        label: 'Temporary Privacy Rules',
        description: 'Restrict quote bait and personal pile-ons.',
        effects: { trust: 7, quality: 5, drama: 5, growth: -3 },
        consequence: 'The rules calm the panic while users debate what counts as bait.',
        tags: ['restrict', 'journalist'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'perform_for_press',
        label: 'Perform for the Press',
        description: 'Become quote-worthy on purpose.',
        effects: { growth: 12, reputation: 5, drama: 13, quality: -8 },
        consequence: 'The article has quotes. Too many quotes.',
        tags: ['journalist', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
      {
        id: 'ignore_press_panic',
        label: 'Ignore the Panic',
        description: 'Trust the community to stay normal enough.',
        effects: { modStress: -2, trust: -2, drama: 4, growth: 3 },
        consequence: 'Most people act normal. The loudest five do not.',
        tags: ['journalist'],
        roleAffinity: 'Growth Hacker',
      },
    ],
  },
  {
    id: 'new_user_orientation',
    arc: 'The New User Exodus arc',
    title: 'Orientation Day Goes Sideways',
    text: 'The community tries a new user orientation thread. Veterans arrive to explain seven incompatible histories.',
    severity: 3,
    tags: ['new-users', 'lore', 'rules'],
    unlockConditions: { minDay: 4, requiredTags: ['new-users'] },
    choices: [
      {
        id: 'official_welcome_guide',
        label: 'Official Welcome Guide',
        description: 'Write one source of truth with fewer legends.',
        effects: { trust: 8, growth: 6, quality: 5, modStress: 6 },
        consequence: 'New users finally have a map. Old users annotate it emotionally.',
        tags: ['new-users', 'quality'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'veteran_buddy_system',
        label: 'Buddy System',
        description: 'Pair newcomers with patient regulars.',
        effects: { trust: 6, growth: 7, modStress: 5, quality: 2 },
        consequence: 'The buddy system works until mentors form a union of sighs.',
        tags: ['new-users', 'growth'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'close_orientation',
        label: 'Close Orientation',
        description: 'Admit the help thread needs help.',
        effects: { quality: 3, modStress: -4, growth: -7, trust: -3 },
        consequence: 'The thread closes, and newcomers return to guessing respectfully.',
        tags: ['new-user-exodus', 'restrict'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'lore_speedrun',
        label: 'Lore Speedrun',
        description: 'Turn orientation into a chaotic history game.',
        effects: { growth: 9, drama: 8, reputation: 4, quality: -3 },
        consequence: 'New users understand nothing but feel included in the confusion.',
        tags: ['new-users', 'lore', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'meme_black_market',
    arc: 'The Meme Economy arc',
    title: 'The Meme Black Market',
    text: 'Users begin trading banned meme formats in coded language like tiny cultural smugglers.',
    severity: 4,
    tags: ['meme', 'ban', 'drama'],
    unlockConditions: { minDay: 5, requiredTags: ['meme'] },
    choices: [
      {
        id: 'amnesty_meme_market',
        label: 'Offer Meme Amnesty',
        description: 'Let contraband jokes surrender peacefully.',
        effects: { trust: 5, drama: -2, quality: -3, modStress: -3 },
        consequence: 'The amnesty clears some contraband and creates a nostalgia thread.',
        tags: ['meme', 'calm'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'double_down_bans',
        label: 'Double Down on Bans',
        description: 'Crack down on coded formats.',
        effects: { quality: 9, drama: 12, trust: -5, modStress: 5 },
        consequence: 'The black market learns poetry and becomes harder to detect.',
        tags: ['ban', 'restrict', 'meme'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'licensed_meme_shop',
        label: 'Open a Licensed Shop',
        description: 'Approve limited meme formats with permits.',
        effects: { growth: 7, quality: 2, drama: 5, modStress: 6 },
        consequence: 'Permits bring order, bureaucracy, and jokes about bureaucracy.',
        tags: ['meme', 'rules'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'meme_market_index',
        label: 'Publish a Meme Index',
        description: 'Track joke value like a financial desk.',
        effects: { growth: 11, reputation: 5, quality: -7, drama: 8 },
        consequence: 'The index becomes popular and immediately manipulated.',
        tags: ['meme', 'growth', 'chaos'],
        roleAffinity: 'Sponsor Gremlin',
      },
    ],
  },
  {
    id: 'algorithm_shadow',
    arc: 'The Algorithm Blessing arc',
    title: 'The Algorithm Looks Away',
    text: 'After a glorious boost, reach suddenly drops. Users blame posting times, vibes, and one suspicious comma.',
    severity: 3,
    tags: ['algorithm', 'growth', 'reputation'],
    unlockConditions: { minDay: 5, requiredTags: ['algorithm'] },
    choices: [
      {
        id: 'quality_reset',
        label: 'Quality Reset',
        description: 'Focus on better posts instead of feed chasing.',
        effects: { quality: 10, trust: 5, growth: -3, reputation: 3 },
        consequence: 'The forum gets better and slightly less obsessed with graph ghosts.',
        tags: ['quality', 'algorithm'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'posting_schedule',
        label: 'Optimise the Schedule',
        description: 'Coordinate posts for maximum feed luck.',
        effects: { growth: 8, reputation: 4, modStress: 5, quality: -2 },
        consequence: 'The schedule helps until users start treating lunch like a launch window.',
        tags: ['algorithm', 'growth'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'panic_content_drive',
        label: 'Panic Content Drive',
        description: 'Ask everyone to post anything with a pulse.',
        effects: { growth: 10, drama: 7, quality: -12, modStress: 6 },
        consequence: 'Reach rises a little. Standards fall down the stairs.',
        tags: ['algorithm', 'quality-drop'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'curse_the_comma',
        label: 'Curse the Comma',
        description: 'Make the suspicious punctuation public enemy one.',
        effects: { drama: 10, growth: 4, reputation: 2, quality: -4 },
        consequence: 'The comma becomes a villain and users start posting grammar theories.',
        tags: ['algorithm', 'meme', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'ama_goes_unhinged',
    arc: 'The Unhinged AMA arc',
    title: 'The AMA Goes Unhinged',
    text: 'An invited guest answers every serious question with unsettling honesty and every joke with a spreadsheet.',
    severity: 5,
    tags: ['ama', 'guest', 'drama'],
    unlockConditions: { minDay: 6 },
    choices: [
      {
        id: 'wrap_ama_early',
        label: 'Wrap It Early',
        description: 'End on a survivable note.',
        effects: { quality: 6, modStress: -5, drama: 7, reputation: -2 },
        consequence: 'The AMA ends, and users debate what question broke the room.',
        tags: ['ama', 'restrict'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'moderated_followup',
        label: 'Moderated Follow-Up',
        description: 'Collect better questions and calmer answers.',
        effects: { reputation: 6, trust: 5, quality: 5, modStress: 6 },
        consequence: 'The follow-up recovers dignity, though the spreadsheet remains canon.',
        tags: ['ama', 'quality'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'let_ama_run',
        label: 'Let It Run',
        description: 'The people demand spectacle.',
        effects: { growth: 14, drama: 16, quality: -9, reputation: 3 },
        consequence: 'The AMA becomes legendary and quoted in future warnings.',
        tags: ['ama', 'chaos', 'growth'],
        roleAffinity: 'Drama Farmer',
      },
      {
        id: 'spreadsheet_theme_week',
        label: 'Spreadsheet Theme Week',
        description: 'Turn the weirdest answer into a festival.',
        effects: { growth: 9, reputation: 6, drama: 7, quality: -4 },
        consequence: 'The community starts rating posts by cell reference.',
        tags: ['ama', 'meme'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'mod_election',
    arc: 'The Mod Team Civil War arc',
    title: 'The Mod Election Proposal',
    text: 'Users propose electing new mods. The current team begins sweating in procedural language.',
    severity: 4,
    tags: ['mod-war', 'vote', 'trust'],
    unlockConditions: { minDay: 6, requiredTags: ['mod-war'] },
    choices: [
      {
        id: 'hold_election',
        label: 'Hold Elections',
        description: 'Let the community choose fresh queue custodians.',
        effects: { trust: 11, drama: 12, modStress: 8, quality: 2 },
        consequence: 'The election energises users and produces campaign slogans nobody needed.',
        tags: ['vote', 'mod-war'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'appoint_review_panel',
        label: 'Appoint a Review Panel',
        description: 'Use a smaller group to vet candidates.',
        effects: { quality: 7, trust: 5, modStress: 5, drama: 5 },
        consequence: 'The panel feels responsible, then becomes the new argument.',
        tags: ['mod-war', 'quality'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'reject_election',
        label: 'Reject the Election',
        description: 'Call moderation an appointment, not a pageant.',
        effects: { modStress: -4, trust: -12, drama: 13, quality: 3 },
        consequence: 'The current team stays, and opposition flair appears overnight.',
        tags: ['mod-war', 'drama'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'mod_reality_show',
        label: 'Run Mod Trials',
        description: 'Make candidates moderate live incidents.',
        effects: { growth: 12, drama: 16, reputation: 4, modStress: 10, quality: -5 },
        consequence: 'The trials are gripping and legally not a good hiring process.',
        tags: ['mod-war', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'bot_civil_rights_thread',
    arc: 'The Bot Invasion arc',
    title: 'The Bot Rights Thread',
    text: 'A philosophical thread asks whether useful bots deserve flair, warnings, or tiny digital citizenship.',
    severity: 3,
    tags: ['bots', 'rules', 'drama'],
    unlockConditions: { minDay: 6, requiredTags: ['bots'] },
    choices: [
      {
        id: 'bot_registry',
        label: 'Create a Bot Registry',
        description: 'Label approved automation clearly.',
        effects: { trust: 7, quality: 7, modStress: 5, drama: 3 },
        consequence: 'The registry helps and gives approved bots a mild celebrity aura.',
        tags: ['bots', 'rules'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'useful_bots_only',
        label: 'Useful Bots Only',
        description: 'Permit helpers, remove bit machines.',
        effects: { quality: 8, trust: 4, growth: -2, modStress: 4 },
        consequence: 'The policy works until everyone defines useful differently.',
        tags: ['bots', 'remove'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'all_bots_are_posts',
        label: 'All Bots Are Content',
        description: 'Let automation compete in the marketplace of attention.',
        effects: { growth: 12, quality: -10, drama: 8, reputation: 3 },
        consequence: 'The marketplace fills with helpful chaos and chaos pretending to help.',
        tags: ['bots', 'growth'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'bot_citizenship_day',
        label: 'Bot Citizenship Day',
        description: 'Hold a ceremonial vote no one can explain.',
        effects: { growth: 8, drama: 11, reputation: 6, quality: -5 },
        consequence: 'The ceremony trends and a bot gives a moving acceptance speech.',
        tags: ['bots', 'chaos', 'meme'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'sponsor_mod_takeover',
    arc: 'The Sponsor Temptation arc',
    title: 'Sponsor Wants a Theme Day',
    text: 'The sponsor asks for a branded theme day where every post must mention optimisation, synergy, or crunch.',
    severity: 4,
    tags: ['sponsor', 'theme', 'quality'],
    unlockConditions: { minDay: 7, requiredTags: ['sponsor'] },
    choices: [
      {
        id: 'one_opt_in_thread',
        label: 'One Opt-In Thread',
        description: 'Contain the brand energy to a labelled box.',
        effects: { growth: 6, reputation: 4, trust: 2, quality: -2, modStress: 3 },
        consequence: 'The sponsor gets visibility and users get an escape hatch.',
        tags: ['sponsor', 'rules'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'refuse_theme_day',
        label: 'Refuse Theme Day',
        description: 'No brand shall own the calendar.',
        effects: { trust: 9, quality: 5, growth: -4, reputation: 2 },
        consequence: 'The community cheers, and the sponsor starts saying partnership journey.',
        tags: ['sponsor', 'quality'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'full_theme_day',
        label: 'Full Theme Day',
        description: 'Paint the whole forum in sponsor-scented content.',
        effects: { growth: 15, reputation: 8, trust: -12, quality: -13, drama: 10 },
        consequence: 'The money is real. So is the community nausea.',
        tags: ['sponsor', 'quality-drop'],
        roleAffinity: 'Sponsor Gremlin',
      },
      {
        id: 'parody_theme_day',
        label: 'Parody Theme Day',
        description: 'Accept the theme and let users roast it.',
        effects: { growth: 10, drama: 9, reputation: 5, trust: -3, quality: -4 },
        consequence: 'The sponsor calls it engagement through gritted teeth.',
        tags: ['sponsor', 'meme', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'archive_lore_war',
    arc: 'The Ancient Forum Lore arc',
    title: 'The Archive Disagrees',
    text: 'Someone finds old posts proving the community has always argued about the thing everyone says is new.',
    severity: 2,
    tags: ['lore', 'archive', 'trust'],
    unlockConditions: { minDay: 7, requiredTags: ['lore'] },
    choices: [
      {
        id: 'publish_lore_timeline',
        label: 'Publish a Timeline',
        description: 'Show the cycle with dates and mercy.',
        effects: { trust: 6, quality: 7, reputation: 4, modStress: 3 },
        consequence: 'The timeline is useful and mildly humiliating for everyone.',
        tags: ['lore', 'quality'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'archive_amnesty',
        label: 'Archive Amnesty',
        description: 'Let old contradictions exist without trials.',
        effects: { trust: 5, drama: -4, modStress: -2 },
        consequence: 'The amnesty calms the thread and frustrates the receipt collectors.',
        tags: ['lore', 'calm'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'weaponise_receipts',
        label: 'Weaponise Receipts',
        description: 'Pin the evidence and let history fight.',
        effects: { drama: 12, growth: 6, reputation: 3, trust: -5 },
        consequence: 'History fights dirty and brings hyperlinks.',
        tags: ['lore', 'drama'],
        roleAffinity: 'Drama Farmer',
      },
      {
        id: 'delete_old_archive_links',
        label: 'Delete Archive Links',
        description: 'Stop archaeological warfare.',
        effects: { modStress: -3, quality: -5, trust: -8, drama: 8 },
        consequence: 'The links disappear, and users start quoting from memory badly.',
        tags: ['remove', 'lore', 'restrict'],
        roleAffinity: 'Banhammer Enthusiast',
      },
    ],
  },
  {
    id: 'quality_strike',
    arc: 'The New User Exodus arc',
    title: 'The Quality Posters Go on Strike',
    text: 'The best contributors stop posting until the community fixes low-effort noise and reply sludge.',
    severity: 5,
    tags: ['quality', 'strike', 'growth'],
    unlockConditions: { minDay: 8, stats: { quality: { max: 45 } } },
    choices: [
      {
        id: 'raise_standards',
        label: 'Raise Standards',
        description: 'Tighten rules to win quality posters back.',
        effects: { quality: 14, trust: 5, growth: -8, modStress: 8, drama: 5 },
        consequence: 'The good posts return, carrying very specific demands.',
        tags: ['quality', 'restrict'],
        roleAffinity: 'Quality Purist',
      },
      {
        id: 'creator_roundtable',
        label: 'Creator Roundtable',
        description: 'Ask top contributors what would help.',
        effects: { trust: 8, quality: 8, modStress: 6, reputation: 4 },
        consequence: 'The roundtable produces useful fixes and one paragraph about vibes.',
        tags: ['quality', 'trust'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'ignore_quality_strike',
        label: 'Ignore the Strike',
        description: 'Assume the feed will replace them.',
        effects: { growth: 8, quality: -10, trust: -9, drama: 6 },
        consequence: 'The feed replaces them with volume and a faint burning smell.',
        tags: ['quality-drop', 'growth'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'pay_with_flair',
        label: 'Pay Them With Flair',
        description: 'Offer status instead of structural change.',
        effects: { growth: 5, reputation: 3, quality: 2, drama: 8, trust: -4 },
        consequence: 'The flair is shiny. The strike notices the missing substance.',
        tags: ['quality', 'sponsor'],
        roleAffinity: 'Sponsor Gremlin',
      },
    ],
  },
  {
    id: 'trust_crater_meeting',
    arc: 'The Mod Team Civil War arc',
    title: 'Emergency Trust Meeting',
    text: 'Trust is low enough that users begin fact-checking the daily greeting.',
    severity: 5,
    tags: ['trust', 'mod-war', 'crisis'],
    unlockConditions: { minDay: 8, stats: { trust: { max: 30 } } },
    choices: [
      {
        id: 'public_repair_plan',
        label: 'Public Repair Plan',
        description: 'Commit to visible fixes and deadlines.',
        effects: { trust: 14, modStress: 8, reputation: 5, drama: -2 },
        consequence: 'The plan is welcomed, then tracked with terrifying precision.',
        tags: ['trust', 'quality'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'ask_for_patience',
        label: 'Ask for Patience',
        description: 'Buy time without promising miracles.',
        effects: { trust: 4, drama: 4, modStress: -2 },
        consequence: 'Some users grant patience. Others ask where patience is stored.',
        tags: ['trust'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'ban_bad_faith',
        label: 'Ban Bad Faith',
        description: 'Remove comments that assume the worst.',
        effects: { quality: 6, trust: -6, drama: 12, modStress: 3 },
        consequence: 'The worst comments vanish and the phrase bad faith becomes explosive.',
        tags: ['ban', 'restrict', 'trust'],
        roleAffinity: 'Banhammer Enthusiast',
      },
      {
        id: 'trust_game_show',
        label: 'Trust Game Show',
        description: 'Answer accusations live with buzzers.',
        effects: { growth: 9, drama: 14, reputation: 3, trust: -3 },
        consequence: 'The show is funny, unwise, and clipped immediately.',
        tags: ['chaos', 'trust'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'drama_overflow',
    arc: 'The Meme Economy arc',
    title: 'Drama Overflow Alert',
    text: 'Every unrelated post now redirects to the same argument by comment three.',
    severity: 5,
    tags: ['drama', 'crisis', 'comments'],
    unlockConditions: { minDay: 8, stats: { drama: { min: 70 } } },
    choices: [
      {
        id: 'argument_quarantine',
        label: 'Quarantine the Argument',
        description: 'Move the recurring fight into one containment thread.',
        effects: { drama: -12, quality: 8, modStress: 6, trust: 3 },
        consequence: 'The fight stays mostly contained and begins naming its own subthreads.',
        tags: ['quarantine', 'restrict', 'drama'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'cooldown_weekend',
        label: 'Cooldown Weekend',
        description: 'Pause hot topics and let the forum hydrate.',
        effects: { drama: -15, trust: 5, growth: -5, modStress: -4 },
        consequence: 'The forum rests, except for one thread debating hydration.',
        tags: ['calm', 'restrict'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'debate_tournament',
        label: 'Debate Tournament',
        description: 'Make the recurring fight official content.',
        effects: { growth: 12, drama: 16, quality: -8, reputation: 4 },
        consequence: 'The tournament crowns a winner, then nobody accepts the bracket.',
        tags: ['drama', 'growth', 'chaos'],
        roleAffinity: 'Drama Farmer',
      },
      {
        id: 'mass_remove_derails',
        label: 'Mass Remove Derails',
        description: 'Delete off-topic argument branches quickly.',
        effects: { quality: 10, drama: 8, trust: -5, modStress: 7 },
        consequence: 'Threads become readable and the removed users start a meta bonfire.',
        tags: ['remove', 'restrict', 'quality'],
        roleAffinity: 'Banhammer Enthusiast',
      },
    ],
  },
  {
    id: 'reputation_summit',
    arc: 'The Journalist Watching arc',
    title: 'The Reputation Summit',
    text: 'Outside communities start citing this forum as either a model or a cautionary mural.',
    severity: 4,
    tags: ['reputation', 'journalist', 'public'],
    unlockConditions: { minDay: 9, stats: { reputation: { min: 65 } } },
    choices: [
      {
        id: 'publish_best_practices',
        label: 'Publish Best Practices',
        description: 'Turn hard lessons into a clean public guide.',
        effects: { reputation: 12, quality: 6, modStress: 5, trust: 3 },
        consequence: 'The guide is praised and immediately nitpicked by people with tabs open.',
        tags: ['reputation', 'quality'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'stay_humble',
        label: 'Stay Humble',
        description: 'Avoid becoming a thinkpiece with buttons.',
        effects: { trust: 6, reputation: 4, drama: -3 },
        consequence: 'The community avoids grandstanding and quietly enjoys being cited.',
        tags: ['reputation', 'calm'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'brand_the_method',
        label: 'Brand the Method',
        description: 'Name the community playbook and sell the aura.',
        effects: { reputation: 10, growth: 10, quality: -4, trust: -3 },
        consequence: 'The method gains a logo and loses a little dignity.',
        tags: ['reputation', 'sponsor'],
        roleAffinity: 'Sponsor Gremlin',
      },
      {
        id: 'start_advice_column',
        label: 'Start an Advice Column',
        description: 'Let other forums ask for help publicly.',
        effects: { growth: 8, reputation: 8, drama: 6, modStress: 6 },
        consequence: 'The advice is good, except when people follow it too literally.',
        tags: ['growth', 'reputation'],
        roleAffinity: 'Growth Hacker',
      },
    ],
  },
  {
    id: 'stress_burnout_alarm',
    arc: 'The Mod Team Civil War arc',
    title: 'The Burnout Alarm',
    text: 'Mods start signing messages with accidental resignation energy.',
    severity: 5,
    tags: ['stress', 'mods', 'crisis'],
    unlockConditions: { minDay: 9, stats: { modStress: { min: 70 } } },
    choices: [
      {
        id: 'mod_sabbatical',
        label: 'Mod Sabbatical',
        description: 'Rotate duties and force rest before collapse.',
        effects: { modStress: -16, trust: 5, quality: -2, growth: -3 },
        consequence: 'The team breathes, and users learn the queue is not self-cleaning.',
        tags: ['mods', 'calm'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'automate_triage',
        label: 'Automate Triage',
        description: 'Let filters handle the obvious stuff.',
        effects: { modStress: -10, quality: 4, trust: -2, drama: 4 },
        consequence: 'Automation helps, then misreads a joke with great confidence.',
        tags: ['bots', 'mods'],
        roleAffinity: 'Algorithm Whisperer',
      },
      {
        id: 'lower_standards',
        label: 'Lower Standards Temporarily',
        description: 'Let more borderline content slide.',
        effects: { modStress: -12, quality: -12, growth: 7, trust: -4 },
        consequence: 'The queue shrinks and the comment section gets crunchier.',
        tags: ['quality-drop', 'growth'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'public_stress_meter',
        label: 'Public Stress Meter',
        description: 'Show the community how close the team is to smoke.',
        effects: { trust: 7, drama: 7, modStress: -5, reputation: 3 },
        consequence: 'The meter inspires empathy and several jokes about red zones.',
        tags: ['mods', 'drama'],
        roleAffinity: 'Drama Farmer',
      },
    ],
  },
  {
    id: 'growth_zero_watch',
    arc: 'The New User Exodus arc',
    title: 'The Empty Welcome Mat',
    text: 'New posts slow down and the welcome thread starts echoing.',
    severity: 5,
    tags: ['growth', 'new-users', 'crisis'],
    unlockConditions: { minDay: 9, stats: { growth: { max: 20 } } },
    choices: [
      {
        id: 'revive_with_event',
        label: 'Revive With an Event',
        description: 'Give people a clear reason to return.',
        effects: { growth: 14, trust: 4, modStress: 6, quality: -2 },
        consequence: 'The event brings people back, including one person still angry from day two.',
        tags: ['growth', 'new-users'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'ask_lurkers',
        label: 'Ask the Lurkers',
        description: 'Invite quiet readers to say what would help.',
        effects: { trust: 7, growth: 6, quality: 4, modStress: 4 },
        consequence: 'Lurkers speak softly and deliver excellent notes.',
        tags: ['new-users', 'trust'],
        roleAffinity: 'Community Therapist',
      },
      {
        id: 'relax_rules_for_week',
        label: 'Relax Rules for a Week',
        description: 'Lower the entry barrier temporarily.',
        effects: { growth: 12, quality: -9, drama: 6, trust: -2 },
        consequence: 'New posts return, some of them wearing muddy shoes.',
        tags: ['growth', 'quality-drop'],
        roleAffinity: 'Sponsor Gremlin',
      },
      {
        id: 'declare_ghost_town_bit',
        label: 'Declare Ghost Town Bit',
        description: 'Make the emptiness funny enough to fill.',
        effects: { growth: 8, drama: 5, reputation: 4, quality: -3 },
        consequence: 'The joke works, and users post tumbleweed memes with punctuality.',
        tags: ['meme', 'growth', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
  {
    id: 'day_30_audit',
    arc: 'The Journalist Watching arc',
    title: 'The Final Audit Looms',
    text: 'The season is nearly over. Users want one last decision to define what the forum became.',
    severity: 5,
    tags: ['finale', 'reputation', 'trust'],
    unlockConditions: { minDay: 28 },
    choices: [
      {
        id: 'community_charter',
        label: 'Write a Charter',
        description: 'Turn the season into principles people can remember.',
        effects: { trust: 10, quality: 8, reputation: 8, modStress: 5 },
        consequence: 'The charter lands well, despite one clause becoming a meme.',
        tags: ['finale', 'quality'],
        roleAffinity: 'Peacekeeper',
      },
      {
        id: 'growth_victory_lap',
        label: 'Take a Victory Lap',
        description: 'Celebrate the numbers and invite everyone in.',
        effects: { growth: 12, reputation: 8, drama: 6, quality: -3 },
        consequence: 'The lap is fun and slightly too loud for a closing argument.',
        tags: ['finale', 'growth'],
        roleAffinity: 'Growth Hacker',
      },
      {
        id: 'strict_final_cleanup',
        label: 'Strict Final Cleanup',
        description: 'End the season with the queue pristine.',
        effects: { quality: 12, modStress: 9, drama: 7, trust: -3 },
        consequence: 'The forum looks polished and everyone can see the broom marks.',
        tags: ['finale', 'restrict'],
        roleAffinity: 'Rule Lawyer',
      },
      {
        id: 'final_chaos_festival',
        label: 'Final Chaos Festival',
        description: 'One last strange celebration before judgment.',
        effects: { growth: 10, drama: 14, reputation: 5, quality: -7 },
        consequence: 'The festival is memorable, arguable, and impossible to summarize neatly.',
        tags: ['finale', 'chaos'],
        roleAffinity: 'Chaos Goblin',
      },
    ],
  },
] satisfies [GameEvent, ...GameEvent[]];

export const getEventById = (eventId: string): GameEvent =>
  GAME_EVENTS.find((event) => event.id === eventId) ?? GAME_EVENTS[0];

export const getFirstEvent = (): GameEvent => GAME_EVENTS[0];